/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/main.js"],
  theme: {
    extend: {
      fontFamily: {
        primary: "Plus Jakarta Sans",
      },
      colors: {
        "project-black": "hsl(0, 0%, 1%)",
        "medium-brown": "hsl(30, 5%, 45%)",
        "light-cream": "hsl(28, 100%, 97%)",
        "galactic-blue": "hsl(252, 66%, 62%)",
        "summer-yellow": "hsl(28, 89%, 67%)",
        "project-pink": "hsl(0, 79%, 79%)",
        "light-red": "hsl(7, 77%, 66%)",
        "project-cyan": "hsl(172, 46%, 57%)",
        "dark-purple": "hsl(314, 46%, 23%)",
      },
      borderRadius: {
        ten: "0.625rem",
        "twenty-eight": "1.75rem",
      },
      lineHeight: {
        "twenty-six": "1.625rem",
        thirty: "1.875rems",
        "thirty-three": "2.0625rem",
        "forty-five": "2.8125rem",
        fifty: "3.125rem",
        "fifty-five": "3.4375rem",
        "seventy-one": "4.4375rem",
      },
      width: {
        "mobile-avatar": "300px",
        "mobile-container": "91.46667%",
        "mobile-paragraph": "83.09038%",
        "mobile-slide": "72%",
        "tablet-avatar": "364px",
        "tablet-container": "89.71354%",
        "tablet-paragraph": "83.164%",
        "tablet-slide": "min(70.3125%, 540px)",
        "desktop-container": "min(77.15278%, 1111px)",
        "desktop-paragraph": "min(65.70657%, 730px)",
        "cta-paragraph": "min(100%, 540px)",
      },
      height: {
        "one-five-eight": "9.875rem",
        "one-eight-two": "11.375rem",
        "three-six-four": "22.75rem",
      },
      fontSize: {
        "twenty-six": "1.625rem",
        "thirty-two": "2rem",
        forty: "2.5rem",
        "forty-four": "2.75rem",
        "fifty-six": "3.5rem",
      },
      margin: {
        fifteen: "0.9375rem",
        "twenty-three": "1.4375rem",
        "twenty-five": "1.5625rem",
        "twenty-six": "1.625rem",
        "twenty-seven": "1.6875rem",
        thirty: "1.875rem",
        "thirty-four": "2.125rem",
        "eighty-eight": "5.5rem",
        "one-hundred": "6.25rem",
        "one-twenty": "7.5rem",
      },
      padding: {
        thirty: "1.875rem",
        "thirty-four": "2.125rem",
        "forty-five": "2.8125rem",
        "sixty-five": "4.0625rem",
        "ninety-five": "5.9375rem",
      },
      backgroundImage: {
        "apps-pattern": "url('./assets/pattern-apps.svg')",
        "graphic-design-pattern": "url('./assets/pattern-graphic-design.svg')",
        "illustrations-pattern": "url('./assets/pattern-illustrations.svg')",
        "motion-graphics-pattern":
          "url('./assets/pattern-motion-graphics.svg')",
        "photography-pattern": "url('./assets/pattern-photography.svg')",
        "ui-ux-pattern": "url('./assets/pattern-ui-ux.svg')",
      },
      backgroundPosition: {
        "right-top": "right 1.5rem top 1.5rem",
      },
      gap: {
        "mobile-slider": "0.9375rem",
        "tablet-slider": "1.875rem",
        "sixty-nine": "4.3125rem",
      },
    },
  },
  plugins: [],
};
